### ISSUE TITLE
[FEATURE] Capability to customize external resources url

### ISSUE THREAD

**Issue by JeanRessouche** [bunkerity/bunkerweb#188]
**What's needed and why ?**

Lists required for the antibot, blacklist, bad referrers and others are currently downloaded during the runtime.
This is great but, within environment with restricted network access, the download fail & the boot fail or produces many errors.

ex : https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/_generator_lists/bad-referrers.list

**Implementations ideas (optional)**
Additionally to the USE_XXX variables, provide a way to override the hard-coded URLs.
Doing so on disconnected or restricted environment we could use a local server to provide the resources.

thanks !

**Comment by souchprod** [comment]
Hi, a little push on this one, i try to use bunkerity from China and it is almost impossible due to the unavailability or extreme slowness of raw.githubusercontent.com here :(

![image](https://user-images.githubusercontent.com/8854025/145835199-920caaaf-d64f-4017-9dce-9be776f814c6.png)

alternatively, can we disable this feature set with a param ?

**Comment by fl0ppy-d1sk** [comment]
Hello @JeanRessouche,

The new 1.4.0 version now supports custom URL for blacklist and whitelist downloads. You will find more info [here](https://docs.bunkerweb.io/1.4/security-tuning/#blacklisting-and-whitelisting).

**Comment by JeanRessouche** [comment]
Thanks !
