### ISSUE TITLE
Where to get support ?

### ISSUE THREAD

**Issue by fl0ppy-d1sk** [bunkerity/bunkerweb#249]
Please do not use GitHub issues to ask for help.

If you are a company, we do provide enterprise offers like support, consulting, development or partnership around BunkerWeb. Just contact us at [contact@bunkerity.com](mailto:contact@bunkerity.com) if you are interested.

To get free community support you can use the following medias :

- The #help channel of BunkerWeb in the [Discord server](https://discord.com/invite/fTf46FmtyD)
- The help category of [GitHub dicussions](https://github.com/bunkerity/bunkerweb/discussions)
- The [/r/BunkerWeb](https://www.reddit.com/r/BunkerWeb) subreddit
- The [Server Fault](https://serverfault.com/) and [Super User](https://superuser.com/) forums

**Comment by MrCybertux** [comment]
@fl0ppy-d1sk The github disscusion seem to be closed or is it just me? Also maybe open up the subreddit since i am still wainting for posting rights, if needed i can offer to do the moderation.

![image](https://github.com/user-attachments/assets/cf2b9930-61a7-44b2-ba48-16ca81aed948)

Sorry to nekro this but it seems some of the options maybe changed since the initial opening of this issue?

**Comment by styladj1** [comment]
> [@fl0ppy-d1sk](https://github.com/fl0ppy-d1sk) The github disscusion seem to be closed or is it just me? Also maybe open up the subreddit since i am still wainting for posting rights, if needed i can offer to do the moderation.
> 
> ![image](https://github.com/user-attachments/assets/cf2b9930-61a7-44b2-ba48-16ca81aed948)
> 
> Sorry to nekro this but it seems some of the options maybe changed since the initial opening of this issue?

Same for me. No possibility to open a new thread in GitHub discussions
