### ISSUE TITLE
[DOC] Explicitly say that Web UI and autoconf are not compatible

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [bunkerity/bunkerweb#297]
**Description**
I didn't understand that Web UI and autoconf can't be used at the same time. I read "At the moment, the web UI is only supported with the [Docker](https://docs.bunkerweb.io/1.4/integrations/#docker), [Linux](https://docs.bunkerweb.io/1.4/integrations/#linux) and [Ansible](https://docs.bunkerweb.io/1.4/integrations/#ansible) integrations" and thought "I'm using Docker so I'm good", without understanding that autoconf is a different integration.

**Proposal (optional)**
Adding in the "supported integrations" box at the top of the Web UI page "It is not possible to use Web UI with autoconf"

**Comment by fl0ppy-d1sk** [comment]
Hello @LeVraiRoiDHyrule,

It should be fixed in the last [v1.4.4 release](https://github.com/bunkerity/bunkerweb/releases/tag/v1.4.4), we updated the [web Ui doc](https://docs.bunkerweb.io/1.4/web-ui/) : 

`
At the moment, the web UI is only supported with the Docker, Linux and Ansible integrations. It's not possible to use the web UI with other integrations like Docker autoconf, Swarm or Kubernetes. Please note that we plan to support more integrations as the project evolves.
`
