### ISSUE TITLE
[BUG] DNSBL

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerweb#395]
**Description**
All default DNSBL domains seems to be down.

**How to reproduce**
```yaml
- DNS_RESOLVERS=1.1.1.1 1.0.0.1
- USE_DNSBL=yes
```

**Logs**
```bash
2022/12/20 00:45:33 [error] 435#435: *490231 [DNSBL] Error while asking DNSBL server problems.dnsbl.sorbs.net : failed to receive reply from UDP server 1.1.1.1:53: timeout, client: XXX.XXX.XXX.XXX, server: nextcloud.XXXX.XXX, request: "GET /ocs/v2.php/apps/serverinfo/api/v1/info HTTP/1.1", host: "nextcloud.XXXX.XXX"
```

```bash
user@user:~$ nslookup bl.blocklist.de 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
*** Can't find bl.blocklist.de: No answer

user@user:~$ nslookup problems.dnsbl.sorbs.net 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
*** Can't find problems.dnsbl.sorbs.net: No answer

user@user:~$ nslookup sbl.spamhaus.org 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
*** Can't find sbl.spamhaus.org: No answer

user@user:~$ nslookup xbl.spamhaus.org 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
*** Can't find xbl.spamhaus.org: No answer

user@user:~$ nslookup google.com 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	google.com
Address: 142.250.75.238
Name:	google.com
Address: 2a00:1450:4007:819::200e

```

**Comment by TheophileDiot** [comment]
Hi, thank you for your issue. It looks like they are down yeah (I tried doing the nslookup myself)

**Comment by TheophileDiot** [comment]
Hi @thelittlefireman, any news on this issue ?

**Comment by TheSiman** [comment]
(note: while I use spamhaus as an example, this should apply to all compliant DNSBLs)
Hi I've been playing around with the DNSBL feature for a bit and I _think_ this issue is missing the point a bit, you're not supposed to be resolving "zen.spamhaus.org" alone for example, there you will get "noerror" and not much else, from my understanding of DNSBL (which is a couple hours of fooling around with it, so take it with a huge grain of salt), you're supposed to query a specific ip, in a format `<ip reversed>.zen.spamhaus.org` for example. So from my understanding this is not a problem and working as intended. (nslookup without arguments returns A and AAAA records, these subdomains don't have them by design)

However I think we're missing the forest for the trees here, if you read the original report, it says that the dns request timed out, and indeed from my testing **bl.blocklist.de** and **problems.dnsbl.sorbs.net** have huge latency, sometimes in order of seconds which seems to be the cause of the timeout, so far I haven't been able to reproduce a timeout with spamhaus servers.

Again I must stress that I have not devoted enough time to this yet, these are just my quick observations, I will try to get back to this to verify my assumptions.

Sources:
https://www.spamhaus.org/faq/section/DNSBL%20Usage#243 (a deeper dive + usage examples)
https://www.geekersdigest.com/what-is-dnsbl-how-do-they-work-fight-against-spam-mails/ (usage examples with dig)
