### ISSUE TITLE
[DOC] Not easily integrate database

### ISSUE THREAD

**Issue by x3nomorpheus** [bunkerity/bunkerweb#552]
**Description**
Hi folks! I don't find any related info about this issue. Is it even real to set up mariadb backend in linux integration? As I research the startup scripts and other info I realized, that it is can not be implemented. Also I didn't find anything info about that in docs. Am I right or I missed something and trying to ask so dummy question?
Installation was done with rpm from official repo.

**Comment by TheophileDiot** [comment]
Hi @x3nomorpheus, thank you for opening this issue. It can be done by setting the right sqlalchemy string value for the setting `DATABASE_URI`. If you have a MySQL database in the same machine, the string will look like this : `mysql+pymysql://user:secret@localhost:3306/db`

**Comment by x3nomorpheus** [comment]
DATABASE_URI=mariadb+pymysql://bwuser:my_secret@localhost:3306/bwdb
In fact, I use the same URI in docker integration and it's work fine. 
But when I manually trying (and also with startup the whole daemon service) to launch init of db it anyway setting up the sqlite db:
`sudo -E -u nginx -g nginx /bin/bash -c "PYTHONPATH=/usr/share/bunkerweb/deps/python/ /usr/share/bunkerweb/gen/save_config.py --variables /tmp/env --init"`
`[2023-07-05 17:28:03] - GENERATOR - ℹ  - Save config started ...
[2023-07-05 17:28:03] - GENERATOR - ℹ  - Settings : /usr/share/bunkerweb/settings.json
[2023-07-05 17:28:03] - GENERATOR - ℹ  - Core : /usr/share/bunkerweb/core
[2023-07-05 17:28:03] - GENERATOR - ℹ  - Plugins : /etc/bunkerweb/plugins
[2023-07-05 17:28:03] - GENERATOR - ℹ  - Init : True
[2023-07-05 17:28:03] - GENERATOR - ℹ  - Detected Linux integration
[2023-07-05 17:28:03] - GENERATOR - ℹ  - Checking arguments ...
[2023-07-05 17:28:03] - GENERATOR - ℹ  - Variables : /tmp/env
[2023-07-05 17:28:03] - GENERATOR - ℹ  - Computing config ...
[2023-07-05 17:28:03] - GENERATOR - ℹ  - Database connection established
[2023-07-05 17:28:03] - GENERATOR - ℹ  - Database is already initialized, skipping ...`

**Comment by TheophileDiot** [comment]
@x3nomorpheus I'll try all this and let you know if I find a viable solution to this, thank you  😁

**Comment by TheophileDiot** [comment]
@x3nomorpheus Turns out there was a bug which made the database change impossible between 2 reloads (it will be fix in the next version). What I can advise you is to restart from scratch with the `DATABASE_URI` directly set to the right value.

As for a little tutorial to connect a database in Linux (in local) I would advice the following :

1. Connect to your database :
`sudo mysql` or `mysql -u root -p`

2. Create the `bunkerweb` user (***remember to set a secure password***):
```mysql
CREATE USER 'bunkerweb'@'localhost' IDENTIFIED BY 'password';
```

3. Create the `bunkerweb` database:
```mysql
CREATE DATABASE bunkerweb
```

4. Grant privileges to the database `bunkerweb` to the user `'bunkerweb'@'localhost'`:
```mysql
GRANT ALL PRIVILEGES ON bunkerweb.* TO 'bunkerweb'@'localhost' WITH GRANT OPTION;
```

5. Always flush the privileges after make a privileges change with mysql:
```mysql
FLUSH PRIVILEGES;
```

And after this you should be good to go with this `DATABASE_URI`:
```
DATABASE_URI=mysql+pymysql://bunkerweb:password@localhost:3306/bunkerweb
```

If you have any questions feel free to ping me or join the [discord server](https://discord.bunkerweb.io/) 😁

**Comment by x3nomorpheus** [comment]
Yeah, thank you so much, it was too important for me. I want to express my gratitude to you!
