### ISSUE TITLE
[question] Bunkerweb & mailcow: How can I mount the generated certs for an external service? Where are they saved ?

### ISSUE THREAD

**Issue by cocoonkid** [bunkerity/bunkerweb#756]
[question] Bunkerweb & mailcow: How can I mount the generated certs for an external service? Where are they saved ?

Thanks in advance

**Comment by cocoonkid** [comment]
Okay I got this pretty much working now.

**Comment by kovacs-andras** [comment]
@cocoonkid please, could you share more details with us?
Could you make Bunkerweb & mailcow work?

**Comment by cocoonkid** [comment]
Yes, I was able to make it work. Now I only need to find out which way I can generate the certs for SMTP and IMAP in the most efficient way. Since SKIP_LETS_ENCRYPT=y in mailcow.conf skips all cert generation.

**Comment by kovacs-andras** [comment]
Super cool, thanks!

**Comment by kovacs-andras** [comment]
@cocoonkid sorry for bugging, could you proceed further with mailcow?

**Comment by cocoonkid** [comment]
@kovacs-andras Sorry I have so much on my plate rn. Yes it works, but I did not continue yet.
Shoot me a message on x if you need any help.

**Comment by eddyJK** [comment]
Hello @kovacs-andras,
hello all,

to provide the the certificates obtained by bunkerweb lets-encrypt plugin one can use
`docker cp -L`
*-L because in .../live/... you find the latest certs and keys as symlink.
Within the container the path is:
`/var/cache/bunkerweb/letsencrypt/etc/live/[bunkerweb-service]`

mailcow expects other filenames then directly provided by certbot.

Check manually if your DNS TLSA key needs to be updated.

Hope this bash example for specifically mailcow helps and answers the question.
You can trigger this script via systemd timer or cronjob on your docker host with root rights, as required for mailcow. For other services you can remove the sudo and run with user rights.

```
#!/bin/bash

set -uvx

#copy private key file
sudo docker cp -L bunkerweb-bw-scheduler-1:/var/cache/bunkerweb/letsencrypt/etc/live/mail.example.com/privkey.pem /opt/mailcow-dockerized/data/assets/ssl/key.pem

#copy fullchain cert file
sudo docker cp -L bunkerweb-bw-scheduler-1:/var/cache/bunkerweb/letsencrypt/etc/live/mail.example.com/fullchain.pem`/opt/mailcow-dockerized/data/assets/ssl/cert.pem

#reload 3 affected 
sudo docker restart $(docker ps -qaf name=postfix-mailcow)
sudo docker restart $(docker ps -qaf name=nginx-mailcow)
sudo docker restart $(docker ps -qaf name=dovecot-mailcow)

#view tlsa deduced from private key, and the TLSA entry provided by via DNS
#Update DNS entry if not equal manually
sudo openssl ec -in /opt/mailcow-dockerized/data/assets/ssl/key.pem -pubout -outform DER | sha256sum
dig _25._tcp.mail.example.com. TLSA | grep ";; ANSWER SECTION:" -A 1
```
