### ISSUE TITLE
[Security enhancement] : migrate from nginx compile with Openssl to Libressl

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerweb#78]
Hi,
Could it be possible to rebuild nginx to use Libressl instead of Openssl ?

Libressl if fork of Openssl made by openBSD guys who managed to get it more secure : [https://en.m.wikipedia.org/wiki/LibreSSL#Changes](https://en.m.wikipedia.org/wiki/LibreSSL#Changes)
Thanks

**Comment by TheSiman** [comment]
Hi,

if this is still being considered to any degree, please re-evaluate if this even makes sense, in the past years libressl has lost most of it's momentum and openssl is considered an industry standard. Many (actually most) projects that migrated to (or supported) libressl have since migrated back to openssl or deprecated libressl support, as an example gentoo comes to mind (https://wiki.gentoo.org/wiki/LibreSSL).

I think there should be a very good reasoning to move from openssl to libressl as a default, especially since openssl is a much more widely used and active project. Adding libressl as an alternative with instructions doesn't sound too bad, but then the project will be expected to support two different ssl implementations that don't have a complete API compatibility.

@thelittlefireman Just to note, these are just my opinions and I am not an expert on cryptography, could you please provide your insight, granted you're still interested in this change? (I am also obviously not affiliated with the project, just a user interested in its future and security)

Thanks,
Simon

**Comment by fl0ppy-d1sk** [comment]
Hi @TheSiman,

Thanks for the info about Gentoo and LibreSSL, that's interesting. Looks like Alpine Linux and Python did the same thing too.

In the early days of the project we made the choice of compiling nginx from source with the aim to include that kind of "tweaks" (alternative libs, hardened compilation, remove some modules, ...) and I think that's why @thelittlefireman suggested to use LibreSSL.

But then we decided to use the official/prebuilt packages and focus on web security, integrations, user interface, ... Unless we have huge advantages to compile it from source again (and only using LibreSSL is not enough IMO) and time to focus on it, the maintainer team won't do it. As a side note, using OpenResty instead of nginx is something we think about.

I'm closing the issue but don't forget that BW is open source and we will be more than happy if someone forks it to make a "libressl flavor" !
